name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest test_app.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/***/Python-Action

            # Ensure git repo is up-to-date
            git pull origin main

            # Create a virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
            python3 -m venv venv
            fi

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies inside the virtual environment
            pip install -r requirements.txt

            # Deactivate the virtual environment
            deactivate

            # Restart the service
            sudo systemctl restart myapp.service

